const locations = {
    "i.2": { description: "Du betrittst den Shop." },
    "i.3": { description: "Du befindest dich im Dorf der Anfänge." },
    "i.4": { description: "Du betrittst den Kreuzung." },
    "j.4": { description: "Du betrittst den Wald." },
    "k.4": { description: "Du betrittst die Wald 2" },
    "k.3": { description: "Du betrittst die Wald 3" },
    "k.2": { description: "Du betrittst die Wald 4" },
    "l.4": { description: "Du betrittst die Wald 5" },
    "l.3": { description: "Du betrittst die Wald 6" },
    "l.2": { description: "Du betrittst die Wald 7" },
    "m.4": { description: "Du betrittst die Wald 8" },
    "m.3": { description: "Du betrittst die Wald 9" },
    "m.2": { description: "Du betrittst die Wald 10" },
    "n.4": { description: "Du betrittst die Wald 11" },
    "n.3": { description: "Du betrittst die Wald 12" },
    "n.2": { description: "Du betrittst die Wald 13" },
    "n.5": { description: "Du betrittst die Wald 14" },
    "o.5": { description: "Du betrittst die Wald 15" },
    "p.5": { description: "Du betrittst die Wald 16" },
    "h.4": { description: "Du betrittst die Höhle" },
    "g.4": { description: "Du betrittst die Höhle 2" },
    "g.3": { description: "Du betrittst die Höhle 3" },
    "g.2": { description: "Du betrittst die Höhle 4" },
    "f.4": { description: "Du betrittst die Höhle 5" },
    "f.3": { description: "Du betrittst die Höhle 6" },
    "f.2": { description: "Du betrittst die Höhle 7" },
    "e.4": { description: "Du betrittst die Höhle 8" },
    "e.3": { description: "Du betrittst die Höhle 9" },
    "e.2": { description: "Du betrittst die Höhle 10" },
    "d.4": { description: "Du betrittst die Höhle 11" },
    "d.3": { description: "Du betrittst die Höhle 12" },
    "d.2": { description: "Du betrittst die Höhle 13" },
    "d.5": { description: "Du betrittst die Höhle 14" },
    "c.5": { description: "Du betrittst die Höhle 15" },
    "b.5": { description: "Du betrittst die Höhle 16" },
    "i.5": {
        description: "Du betrittst die Stadt 1",
        chest: {
            contents: ["Heiltrank", "Goldmünzen", "Schwert"],
        },
    },
    "i.6": { description: "Du betrittst die Stadt 2" },
    "i.7": { description: "Du betrittst die Stadt 3" },
    "i.8": { description: "Du betrittst die Stadt 4" },
    "j.6": { description: "Du betrittst die Stadt 5" },
    "j.7": { description: "Du betrittst die Stadt 6" },
    "j.8": { description: "Du betrittst die Stadt 7" },
    "k.6": { description: "Du betrittst die Stadt 8" },
    "k.7": { description: "Du betrittst die Stadt 9" },
    "k.8": { description: "Du betrittst die Stadt 10" },
    "l.6": { description: "Du betrittst die Stadt 11" },
    "l.7": { description: "Du betrittst die Stadt 12" },
    "l.8": { description: "Du betrittst die Stadt 13" },
    "l.9": { description: "Du betrittst die Stadt 14" },
    "m.9": { description: "Du betrittst die Stadt 15" },
    "n.9": { description: "Du betrittst die Stadt 16" },
};

module.exports = locations;
